package me.skizzme.cc.shop.category.impl;

import me.skizzme.cc.shop.category.Category;
import net.minecraft.item.Item;
import net.minecraft.item.ItemConvertible;
import net.minecraft.item.ItemGroups;
import net.minecraft.item.Items;
import net.minecraft.registry.Registries;

import static net.minecraft.item.Items.*;

import java.util.ArrayList;

public class NatureBlocks extends Category {
    public NatureBlocks() {
        super("Nature Blocks", Items.GRASS_BLOCK);
    }

    @Override
    public ArrayList<ItemConvertible> getItems() {
        ArrayList<ItemConvertible> items = new ArrayList<>();
        for (ItemConvertible i : c_items) {
            Item item = i.asItem();
            if (item == BEDROCK || item.getName().getString().toLowerCase().contains("ore") || item == SCULK_SHRIEKER || item == TURTLE_EGG ||
                    item == SNIFFER_EGG || item == BEE_NEST || item == HONEYCOMB_BLOCK || item == RAW_IRON_BLOCK ||
                    item == RAW_COPPER_BLOCK || item == ANCIENT_DEBRIS || item == RAW_GOLD_BLOCK
            )
                continue;
            items.add(item);
        }
        return items;
    }

    @Override
    public boolean isSellable(ItemConvertible item) {
        return true;
    }

    private static final ItemConvertible[] c_items = {Items.GRASS_BLOCK,
        Items.PODZOL,
        Items.MYCELIUM,
        Items.DIRT_PATH,
        Items.DIRT,
        Items.COARSE_DIRT,
        Items.ROOTED_DIRT,
        Items.FARMLAND,
        Items.MUD,
        Items.CLAY,
        Items.GRAVEL,
        Items.SAND,
        Items.SANDSTONE,
        Items.RED_SAND,
        Items.RED_SANDSTONE,
        Items.ICE,
        Items.PACKED_ICE,
        Items.BLUE_ICE,
        Items.SNOW_BLOCK,
        Items.SNOW,
        Items.MOSS_BLOCK,
        Items.MOSS_CARPET,
        Items.STONE,
        Items.DEEPSLATE,
        Items.GRANITE,
        Items.DIORITE,
        Items.ANDESITE,
        Items.CALCITE,
        Items.TUFF,
        Items.DRIPSTONE_BLOCK,
        Items.POINTED_DRIPSTONE,
        Items.PRISMARINE,
        Items.MAGMA_BLOCK,
        Items.OBSIDIAN,
        Items.CRYING_OBSIDIAN,
        Items.NETHERRACK,
        Items.CRIMSON_NYLIUM,
        Items.WARPED_NYLIUM,
        Items.SOUL_SAND,
        Items.SOUL_SOIL,
        Items.BONE_BLOCK,
        Items.BLACKSTONE,
        Items.BASALT,
        Items.SMOOTH_BASALT,
        Items.END_STONE,
        Items.COAL_ORE,
        Items.DEEPSLATE_COAL_ORE,
        Items.IRON_ORE,
        Items.DEEPSLATE_IRON_ORE,
        Items.COPPER_ORE,
        Items.DEEPSLATE_COPPER_ORE,
        Items.GOLD_ORE,
        Items.DEEPSLATE_GOLD_ORE,
        Items.REDSTONE_ORE,
        Items.DEEPSLATE_REDSTONE_ORE,
        Items.EMERALD_ORE,
        Items.DEEPSLATE_EMERALD_ORE,
        Items.LAPIS_ORE,
        Items.DEEPSLATE_LAPIS_ORE,
        Items.DIAMOND_ORE,
        Items.DEEPSLATE_DIAMOND_ORE,
        Items.NETHER_GOLD_ORE,
        Items.NETHER_QUARTZ_ORE,
        Items.ANCIENT_DEBRIS,
        Items.RAW_IRON_BLOCK,
        Items.RAW_COPPER_BLOCK,
        Items.RAW_GOLD_BLOCK,
        Items.GLOWSTONE,
        Items.AMETHYST_BLOCK,
        Items.BUDDING_AMETHYST,
        Items.SMALL_AMETHYST_BUD,
        Items.MEDIUM_AMETHYST_BUD,
        Items.LARGE_AMETHYST_BUD,
        Items.AMETHYST_CLUSTER,
        Items.OAK_LOG,
        Items.SPRUCE_LOG,
        Items.BIRCH_LOG,
        Items.JUNGLE_LOG,
        Items.ACACIA_LOG,
        Items.DARK_OAK_LOG,
        Items.MANGROVE_LOG,
        Items.MANGROVE_ROOTS,
        Items.MUDDY_MANGROVE_ROOTS,
        Items.CHERRY_LOG,
        Items.MUSHROOM_STEM,
        Items.CRIMSON_STEM,
        Items.WARPED_STEM,
        Items.OAK_LEAVES,
        Items.SPRUCE_LEAVES,
        Items.BIRCH_LEAVES,
        Items.JUNGLE_LEAVES,
        Items.ACACIA_LEAVES,
        Items.DARK_OAK_LEAVES,
        Items.MANGROVE_LEAVES,
        Items.CHERRY_LEAVES,
        Items.AZALEA_LEAVES,
        Items.FLOWERING_AZALEA_LEAVES,
        Items.BROWN_MUSHROOM_BLOCK,
        Items.RED_MUSHROOM_BLOCK,
        Items.NETHER_WART_BLOCK,
        Items.WARPED_WART_BLOCK,
        Items.SHROOMLIGHT,
        Items.OAK_SAPLING,
        Items.SPRUCE_SAPLING,
        Items.BIRCH_SAPLING,
        Items.JUNGLE_SAPLING,
        Items.ACACIA_SAPLING,
        Items.DARK_OAK_SAPLING,
        Items.MANGROVE_PROPAGULE,
        Items.CHERRY_SAPLING,
        Items.AZALEA,
        Items.FLOWERING_AZALEA,
        Items.BROWN_MUSHROOM,
        Items.RED_MUSHROOM,
        Items.CRIMSON_FUNGUS,
        Items.WARPED_FUNGUS,
        Items.SHORT_GRASS,
        Items.FERN,
        Items.DEAD_BUSH,
        Items.DANDELION,
        Items.POPPY,
        Items.BLUE_ORCHID,
        Items.ALLIUM,
        Items.AZURE_BLUET,
        Items.RED_TULIP,
        Items.ORANGE_TULIP,
        Items.WHITE_TULIP,
        Items.PINK_TULIP,
        Items.OXEYE_DAISY,
        Items.CORNFLOWER,
        Items.LILY_OF_THE_VALLEY,
        Items.TORCHFLOWER,
        Items.WITHER_ROSE,
        Items.PINK_PETALS,
        Items.SPORE_BLOSSOM,
        Items.BAMBOO,
        Items.SUGAR_CANE,
        Items.CACTUS,
        Items.CRIMSON_ROOTS,
        Items.WARPED_ROOTS,
        Items.NETHER_SPROUTS,
        Items.WEEPING_VINES,
        Items.TWISTING_VINES,
        Items.VINE,
        Items.TALL_GRASS,
        Items.LARGE_FERN,
        Items.SUNFLOWER,
        Items.LILAC,
        Items.ROSE_BUSH,
        Items.PEONY,
        Items.PITCHER_PLANT,
        Items.BIG_DRIPLEAF,
        Items.SMALL_DRIPLEAF,
        Items.CHORUS_PLANT,
        Items.CHORUS_FLOWER,
        Items.GLOW_LICHEN,
        Items.HANGING_ROOTS,
        Items.FROGSPAWN,
        Items.TURTLE_EGG,
        Items.SNIFFER_EGG,
        Items.WHEAT_SEEDS,
        Items.COCOA_BEANS,
        Items.PUMPKIN_SEEDS,
        Items.MELON_SEEDS,
        Items.BEETROOT_SEEDS,
        Items.TORCHFLOWER_SEEDS,
        Items.PITCHER_POD,
        Items.GLOW_BERRIES,
        Items.SWEET_BERRIES,
        Items.NETHER_WART,
        Items.LILY_PAD,
        Items.SEAGRASS,
        Items.SEA_PICKLE,
        Items.KELP,
        Items.DRIED_KELP_BLOCK,
        Items.TUBE_CORAL_BLOCK,
        Items.BRAIN_CORAL_BLOCK,
        Items.BUBBLE_CORAL_BLOCK,
        Items.FIRE_CORAL_BLOCK,
        Items.HORN_CORAL_BLOCK,
        Items.DEAD_TUBE_CORAL_BLOCK,
        Items.DEAD_BRAIN_CORAL_BLOCK,
        Items.DEAD_BUBBLE_CORAL_BLOCK,
        Items.DEAD_FIRE_CORAL_BLOCK,
        Items.DEAD_HORN_CORAL_BLOCK,
        Items.TUBE_CORAL,
        Items.BRAIN_CORAL,
        Items.BUBBLE_CORAL,
        Items.FIRE_CORAL,
        Items.HORN_CORAL,
        Items.DEAD_TUBE_CORAL,
        Items.DEAD_BRAIN_CORAL,
        Items.DEAD_BUBBLE_CORAL,
        Items.DEAD_FIRE_CORAL,
        Items.DEAD_HORN_CORAL,
        Items.TUBE_CORAL_FAN,
        Items.BRAIN_CORAL_FAN,
        Items.BUBBLE_CORAL_FAN,
        Items.FIRE_CORAL_FAN,
        Items.HORN_CORAL_FAN,
        Items.DEAD_TUBE_CORAL_FAN,
        Items.DEAD_BRAIN_CORAL_FAN,
        Items.DEAD_BUBBLE_CORAL_FAN,
        Items.DEAD_FIRE_CORAL_FAN,
        Items.DEAD_HORN_CORAL_FAN,
        Items.SPONGE,
        Items.WET_SPONGE,
        Items.MELON,
        Items.PUMPKIN,
        Items.CARVED_PUMPKIN,
        Items.JACK_O_LANTERN,
        Items.HAY_BLOCK,
        Items.BEE_NEST,
        Items.HONEYCOMB_BLOCK,
        Items.SLIME_BLOCK,
        Items.HONEY_BLOCK,
        Items.OCHRE_FROGLIGHT,
        Items.VERDANT_FROGLIGHT,
        Items.PEARLESCENT_FROGLIGHT,
        Items.SCULK,
        Items.SCULK_VEIN,
        Items.SCULK_CATALYST,
        Items.SCULK_SHRIEKER,
        Items.SCULK_SENSOR,
        Items.COBWEB,
        Items.BEDROCK
    };
}
